export const apartmentDefaultSchemas = `
            id
            houseUrl
            houseId
            airCondition
            area
            bed
            bizcircle
            buildingTotalFloors
            carport
            checkInDate
            city
            closet
            communityName
            communityUrl
            district
            electricity
            elevator
            floor
            floorAccessibility
            floorFullInfo
            fridge
            gas
            heating
            houseType
            imgUrls
            lat
            lng
            naturalGas
            orient
            price
            pricePerSquareMeter
            subwayAccessibility
            tags
            washingMachine
            water
            waterHeater
            wifi
            title
            createdAt
            createdTime
`;
